### ISSUE TITLE
Replica state priorities

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#134]
Currently, the cluster balancer promotes and demotes replicas in the cluster based solely on their type. Reserve replicas are chosen fairly arbitrarily to be promoted. However, in clusters that span across AZs, users may want to favor promoting certain nodes over others. To support this, priorities should be added to replicas, and available replicas with a higher priority should be promoted over those with lower priorities.

The question is whether an unavailable replica with a high priority which becomes available should replace an active replica with a lower priority. I think this may require some refactoring of the Atomix cluster balancer to support some sort of strategy.

**Comment by jhalterman** [comment]
This idea overlaps with the general area of resource locality, such as where Hadoop clusters (can) track which rack each host resides on in order to place 2 (for example) replicas on one rack for low latency and a 3rd replica on another rack for fault tolerance. Being able to place (some) replicas onto the same rack minimizes network traffic/latency that you'd otherwise encounter if you simply threw them in the same AZ. This is less a concern for Copycat than it is for big data systems, but the same ideas can be exploited.

I've seen a few different ways of modeling this problem, and haven't really found one that I love yet. I'm thinking of maybe tagging nodes with location information such as AZ1, rack2, regionFoo - then providing pluggable strategies that can consider that information when deciding which nodes to use when replacing failed nodes and also, possibly, which nodes to use for the initial cluster formation (ie: you might not want all 3 nodes on the same rack).

**Comment by kuujo** [comment]
Ahh that seems like a good idea. Just provide an abstraction for tagging nodes and strategy to decide what to do when a state change (available/unavailable/join/leave) occurs.

**Comment by jhalterman** [comment]
Yep, something like that.

Typically a big data cluster would use locality to decide which nodes to place certain data sets on, but with Atomix each node is a complete replica, so the decision (I think) would be which nodes to include in the cluster.
