### ISSUE TITLE
Cannot reply with an Exception on the MessageBus

### ISSUE THREAD

**Issue by imperatorx** [atomix/atomix#163]
If a response to a message is an exceptionally completed future, Atomix sends a timeout exception back to the caller. Also, is there a way to set a timeout for the reply? I see now it is hardcoded. Example code:

```
 final Address currentAddress = new Address("127.0.0.1", 6000);

    List<Address> members = Arrays.asList(
            new Address("127.0.0.1", 6000)
    );

    Storage storage = new Storage(StorageLevel.MEMORY);

    Transport transport = NettyTransport.builder().withThreads(4).build();

    AtomixReplica replica = AtomixReplica.builder(currentAddress, members)
            .withStorage(storage)
            .withTransport(transport)
            .withBackupCount(0)
            .build();

    replica.open().join();

    Address address = new Address("127.0.0.1", 6001);

    replica.getMessageBus("bus", new DistributedMessageBus.Options().withAddress(address)).whenComplete((bus, err1) -> {

      bus.consumer("foo", (String msg) -> {

        System.out.println("GOT YOUR REQUEST: " + msg);

        CompletableFuture ret = new CompletableFuture();

        ret.completeExceptionally(new RuntimeException("test error"));
        //ret.complete("test ok");

        return ret;

      }).thenAccept(ignore -> {

        MessageProducer<String> producer = bus.<String>producer("foo").join();

        producer.<String>send("TEST REQUEST" + currentAddress.toString()).whenComplete((reply, err2) -> {

          System.out.println("Response was: " + reply + " err was " + err2);

        });

        System.out.println("REQUEST SENT");

      });

    });
```

**Comment by kuujo** [comment]
This is likely because `RuntimeException` is not serializable. Well, it is serializable obviously, but it's not whitelisted. The Catalyst serializer currently requires whitelisting by default. This will likely be changed in the very near future. It can be disabled by `atomix.serializer().disableWhitelist()`

The reason for requiring whitelisting by default it twofold. First, arbitrary serialization of class names is a security risk. But the larger reason is because it's extremely unperformant. Whitelisting classes enables Catalyst to significantly optimize serialization with numeric types. But this is still going to be changed to disable whitelisting by default. It will be up to users to enable it and/or register classes for the best performance.

**Comment by imperatorx** [comment]
I can confirm, that the serialization was the problem. On the timeout issue:

The NettyConnection class has the _private static final long REQUEST_TIMEOUT = 500;_ hardwired, so if a reply on the _DistributedMessageBus_ takes more than 0.5 seconds to arrive, it will get discarded. Is there a workaround to manually set up this value for the DistributedMessageBus? I want to send messages to business methods which take more than 0.5 sec to complete.

**Comment by kuujo** [comment]
This is an easy change. We can make that timeout configurable. But the problem is, the message bus is using the underlying client/server transport, so configuring the timeout for the transport will mean configuring the transport for clients in the Raft implementation too. There may have to be some way to do per-client configurations. We don't want to have to create more `Transport`s than there are since each transport has its own event loop group/thread pool.

Will commit the serialization fix and come up with something for transport timeouts in Catalyst.

**Comment by kuujo** [comment]
atomix/catalyst#43

**Comment by imperatorx** [comment]
I have the following suggestion to accomplish this with the least change:

-  io.atomix.catalyst.transport.NettyConnection$ContextualFuture could have an optional Long field (timeout)
- io.atomix.catalyst.transport.Connection could have a `<T, U> CompletableFuture<U> send(T message, long timeout);` overload. This sets the ContextualFuture timeout value.
- If a contextual futures timeout is null, the connection default timeout is used by the timeout checker
- If a contextual futures timeout is set, that value is used by the timeout checker
- Add a way to create a io.atomix.messaging.InternalMessageProducer with a custom timeout value
- If a custom timeout value is set at its creation, InternalMessageProducer invokes Connection.send(T message, long timeout) instead of Connection.send(T message) on each send()

**Comment by imperatorx** [comment]
Would you consider these as a pull request?

https://github.com/imperatorx/catalyst/commit/6f2aa74f1732767616338bbc54d8fc6782408072
https://github.com/imperatorx/atomix/commit/cfe00995adf1e2a7c8d2c87dcc2ce70c112024c7
