### ISSUE TITLE
Crashed member does not leave DistributedGroup

### ISSUE THREAD

**Issue by joaocpsantos** [atomix/atomix#164]
I have a test where I'm creating a DistributedGroup and having a few members join.
I then kill one of the java processes and that member never leaves the group members.

I can see that Atomix is detecting the failed member because if I kill the leader, another leader gets elected, but I was expecting it to also remove the killed member from the members list.

In addition, when you have two members on the group and the leader leaves, the remaining member does not become the leader.

Tested on all the rc versions.

**Comment by kuujo** [comment]
There was a bug in `DistributedGroup` when using persistent members. If a member joins the group with e.g. `group.join("foo")` then its state is persisted in the state machine to allow e.g. messages to be redelivered when it rejoins the group. The logic when a persistent member was removed from the group did not allow a new election to occur. This is fixed in #179

I also added some tests to ensure that group members are updated when a persistent or non-persistent member leaves the group. I haven't been able to reproduce any bug wherein a failed member is not removed from the group.
