### ISSUE TITLE
How to iterate a DistributedSet?

### ISSUE THREAD

**Issue by cachenbach** [atomix/atomix#191]
Is it possible to iterate a DistributedSet? Perhaps a "toArray()" method would be great. Or is there any other way to abtain all stored values?

Do you have plans for a DistributedList?

Greetings
 Christian

**Comment by kuujo** [comment]
DistributedList can and should be added. I'll get on that.

So, the idea of iterating collections is being debated. There are problems with any sort of toArray type methods since that implies pulling the entire data structure to the client, and theoretically that could mean pulling an entire server's memory to the client and blocking the server. So, the other option is implementing the stream API. I like this option, but it may require some throttling between the server and client that could imply a loss of consistency. Meaning, the state that's streamed back to the client may not represent the state of the collection at a specific point in time simply because it would be too expensive to send a large collection back to the client at once. Maybe there's room for some configuration that specifies how state should be streamed. Collection state machines could also copy the state prior to streaming it to ensure a single consistent snapshot is sent to the client, but even in that case some consistency can be lost on the client unless the client is blocked until the full stream is received. Anyways, I suppose it's complicated, but is certainly doable once questions about consistency guarantees are answered. I'll likely go check out how some other systems handle this problem and then take a stab at it this week.

**Comment by jhalterman** [comment]
Collections probably should just pull the entire state back (caveat emptor), or at least do so as a default option. Streams may not.

**Comment by jhalterman** [comment]
`DistributedSet.iterator` has been added via #200.

**Comment by cachenbach** [comment]
Amazing! I will try it first thing in the morning.

Thanks
 Christian
