### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by hsaraogi** [atomix/atomix#206]
We need some fixes like https://github.com/atomix/atomix/pull/197.  Can we release the next version soon?

**Comment by robzienert** [comment]
I'm also curious about the state of this repo & org. It looks like it's gone completely abandoned in the last 6 months. Are there plans to continue support or transfer ownership to a new owner?

**Comment by kuujo** [comment]
It's going to be today

**Comment by kuujo** [comment]
It's not and will never be abandoned :-) I just work on multiple large projects now, and only get paid for one of them. I've been finishing a large research project for my company over the last six months and this fell by the wayside, but that's why we have multiple committers already and will likely be adding more from the ONOS project soon.
