### ISSUE TITLE
Joining a DistributedGroup with a duplicate memberId does not throw an exception

### ISSUE THREAD

**Issue by ccleve** [atomix/atomix#225]
```
		DistributedGroup group = replica.getGroup("mynodes").join();
		
		String memberId = "fixedMemberId";
		
		group.join(memberId).whenComplete((localMember, myThrowable) -> {
			System.out.println("join complete");
			System.out.println(localMember);
			System.out.println(myThrowable);
		});
```

Running this code in two different processes does not complete the second process exceptionally when both processes use the same memberId. They both connect successfully.

(I've not tested to see how they interact, or whether they can send messages, etc.)

**Comment by kuujo** [comment]
Hmm... so this is a really good find. The problem here is that the intent of persistent members is for a node to crash and be restarted, thus recovering its state when it reconnects. So, the state machine assumes the second node to rejoin the group is just a second version of the first and therefore replaces the first with the second. This could alternatively be handled by ensuring the first member's session has been unregistered (expired or closed) before the second can join the group. 

I guess those are the two possible behaviors here: the second member overwrites the first or the second member's join is rejected. I think the problem may be if a member's join is rejected due to a duplicate member ID, that will likely mean more frequent errors on recovery. If a client is disconnected/crashes and recovers, its join is likely to get rejected until the prior session is removed, and that's dependent on the session timeout. That means users have to account for the cluster failing to remove a session for some arbitrary amount of time when joining the group. 

There is one way to get around that. The latest release of Copycat added client-provided IDs which can close old sessions when a client opens a new session. That would ensure that when a persistent member rejoins a group, its prior session is already removed, thus removing the potential for errors.

So, I think it probably makes sense to reject joins from member's that still have an open session. Users would have to simply either assign client IDs to ensure the prior session is removed before a join, or retry joins until successful. The retry could be handled internally, but that introduces some inconsistencies - joins are not linearizable with transparent retries. I guess the other alternative is to queue those types of joins in the group state machine and complete them when the prior session is unregistered. That creates a sort of interesting failover feature where multiple clients can join as the same member, but only one client is ever treated as an active member of the group. I like that!

**Comment by ccleve** [comment]
Can you use the host name or ip as a hint as to whether it's the same node trying to rejoin after a restart, or a completely different node trying to join with a conflicting id?

**Comment by kuujo** [comment]
Something like that may be possible, but its use depends on how the member IDs are used. It's perfectly reasonable for a node to crash and for the same logical member to be restarted on a different machine. For example, if I'm sending messages and don't want a member to have to wait for its machine to recover (which could be never), it could instead be restarted on another machine with the same member ID to retrieve lost messages. To ensure all potential use cases are covered it's probably best to just expose the Copycat client ID in the Atomix API. I'll also implement queueing for joining groups, perhaps with options to enable/disable it.
