### ISSUE TITLE
ManagedMembers.close() causes caller to throw NullPointerException

### ISSUE THREAD

**Issue by donmendelson** [atomix/atomix#29]
RaftStateClient.close() invokes ManagedMembers.close() with lambda on the result.
```
      members.close().whenCompleteAsync((result, error) -> {
        if (error == null) {
          future.complete(null);
        } else {
          future.completeExceptionally(error);
        }
      }, context);
```
However, ManagedMembers.close() returns null if permits > 0, causing a NullPointerException to be thrown in the caller.

**Comment by kuujo** [comment]
Good catch!

**Comment by donmendelson** [comment]
ManagedMembers.close() gets called multiple places in code; RaftStateClient.close()  is just one instance. 

My motivation was to close test members in a unit test of consensus. What happens if one cluster node is down, what happens if there is no quorum? In my tests, Copycat.close() throws fails every time with TestCluster. (In an acceptance test of NettyCluster, I would kill processes, of course.)

Consensus is based on how many members are configured for the cluster, not how many are currently alive, correct?

**Comment by donmendelson** [comment]
As an alternative to closing a node, I tried just not opening one or more. Without a majority of configured members, Copycat.open() failed on the client with TimeoutException. Is this intended behavior if the cluster is not healthy?

**Comment by kuujo** [comment]
Right, consensus is based on the number of ACTIVE nodes in the cluster, and that number should always be fixed (until membership changes have been added).

I don't think you should be seeing a TimeOutException and I think timeouts and retries are a work in progress, and it's debatable how various failures should be handled. Our Jepsen tests have proved the correctness of the algorithm but at the same time exposed a lot of inefficiencies in how clients handle servers being down.

This is how failures should be handled currently:

If you're using the Netty cluster, the Netty client has a fixed timeout of 5000 milliseconds. That is, it expects a response within 5000 milliseconds. When the Raft client first starts (every server extends client, and RaftClient is the interface through which operations are submitted to servers) it should attempt to connect to a random Raft server and register a new session. In the event that the cluster times out, it should retry with another random server. (This is one of the areas where there's an inefficiency we've see in Jepsen tests. In a partition/failure where a majority of the cluster is not available, a client will essentially hammer the cluster with attempts to register a new session or keep an existing session alive until the partition/failure is resolved).

Once a client (or server) finds the leader, it should start sending periodic keep alive requests and can submit state changes. If the client fails to communicate with the leader, it should go back to step 1 and start hitting random nodes until it can reach the existing leader or a new leader.

Because all servers are also clients, this behavior applies to both. Essentially, the client is what's exposed to the user, and the fact that a node is a client or a server should be relevant only to Copycat internally. That said, Jepsen tests have used clients and servers in those roles exclusively.

A bit of refactoring is currently being done to help resolve some of the issues with connections between clients and servers. Truthfully, the Cluster abstraction is too high level for Raft, and so it's being moved up to the core module and replaced with lower level Clients, Servers, and Connections to be used by the Raft implementation. Part of the reasoning for this is to allow for bi-directional communication between the client and server (as basically a socket, which doesn't currently exist) but also to allow the Raft implementation to manage connections and their errors more efficiently. For instance, the RaftClientContext will maintain a single Connection to the current leader, and RaftServerContext a set of Connections only to other servers. The Raft implementation will then expose a set of Sessions through which higher level APIs like the Cluster can communicate, and things like timeouts, failures, and retries will be handled differently on the Raft client/server level from the Copycat level.

There may simply be differences in the TestCluster that aren't present in the NettyCluster. All our Jepsen tests have been done on legitimate networks using the NettyCluster, and I'd be curious whether this same behavior exists in that environment. BTW we've basically been using the example server in the examples directory to test via Jepsen.

**Comment by kuujo** [comment]
Recent improvements to configuration changes in Copycat make this issue fixed :-)
