### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by shevek** [atomix/atomix#3]
This library looks excellent. We would really love a Java 7 compatible version on Maven Central. Are you able to do that?

We need 7 as Java 8 isn't in standard Linux distributions yet, and we have downstream customers. I appreciate the niceties of 8 nevertheless, but we can't consume it.

**Comment by tchoulihan** [comment]
Hey @kuujo , could you push a 0.5.0-SNAPSHOT to maven central or somewhere? All of your maven dependencies are currently unusable.

**Comment by kuujo** [comment]
Yep, right you are.

So, I can push that last stablish snapshot, but I don't recommend either version be used for anything but testing. 

The refactoring currently being done is due to a fundamental flaw in log compaction in that version. Once the refactoring of the log and IO is complete, though, there will be a feature freeze (in about a week) and a major testing push and ultimately release. So, that's just an FYI that there are some changes coming shortly and they will comprise the first release.

Still, I'd be interested in feedback if you do play with it. Aside from the log and log compaction, the Raft implementation will remain largely untouched.

**Comment by tchoulihan** [comment]
Where's a stable version then?

All I'm seeing on maven central are these:
```xml
<dependency>
			<groupId>org.onosproject</groupId>
			<artifactId>copycat-netty</artifactId>
			<version>0.4.0.onos</version>
		</dependency>
```

And they seem to be missing a lot of important methods.

**Comment by kuujo** [comment]
Done :-P
