### ISSUE TITLE
How to tell if an Atomix instance is healthy?

### ISSUE THREAD

**Issue by jplock** [atomix/atomix#383]
What would be the recommended way to tell if an Atomix cluster is healthy or not?  Is there a command to ping each node?  Or should I check that there is at least one member in the cluster?

**Comment by kuujo** [comment]
This is a good question. I think we should probably think about what “healthy” means and how we can make it easy to determine whether a node is healthy. The reachability of one node certainly doesn’t seem to indicate a healthy cluster. That node could be partitioned or could be the last node in a cluster that requires at least two nodes for Raft partitions to operate. But if we assume that healthy means the ability to modify state (to form quorums in the Raft partitions), the answer to the question of whether the cluster is healthy could be different for different nodes in the cluster. I.e if a node is partitioned, it could believe the cluster is not healthy because it can’t reach any of the Raft leaders, while the other side of the partition is perfectly healthy and the availability of the cluster is ultimately in no way impacted. So, it may be that a health check can only be node specific or the aggregate of all nodes can indicate something close to the health of the cluster, but one node can not safely indicate the health of the cluster overall.

Anyways, I’m just spitballing. I think it may be important to answer the question of what health is and how to answer health checks. I suspect we could have a few health levels:
• All partitions can be written (total availability)
• All partitions can be read (partial availability)
• Neither of the above (no availability)

Also, the notion of a health check may just be specific to individual nodes, i.e. node 1 is available, node 2 isn’t, the local node cannot write to all partitions, etc. Any of this is totally doable, but requires some thought to implement and document in a way that’s useful for users.

Also relevant here is that the `ClusterService` does show the availability of peers using a failure detection algorithm. 

```
Node node = atomix.clusterService().getNode(“foo”);
Node.State = node.getState();
```

But again, this information is from the perspective of the local node and isn’t a cluster-wide view of the availability of the cluster, which is to some extent impossible.

**Comment by johnou** [comment]
@jplock please close the issue if the above explanation answered your question.
