### ISSUE TITLE
state acquired from metadataService throws UnsupportedOperationException

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [atomix/atomix#396]
to reproduce start atomix service, connect to already running cluster
```
for (Node availableNode : atomix3.metadataService().getMetadata().bootstrapNodes()) {
    logger.info("node {} is in state {}.", availableNode, availableNode.getState());
}
```

I get

```
18:09:51.565 [main] ERROR MDC[] io.carousel.it.Bootstrap - there were problems. sleeping
 java.lang.UnsupportedOperationException: null
    at io.atomix.cluster.Node.getState(Node.java:165) ~[atomix-cluster-2.1.0-SNAPSHOT.jar:?]
    at io.carousel.it.Bootstrap.main(Bootstrap.java:56) [test-classes/:?]
```

but if state is acquired via clusterService, everything is fine
```
for (Node availableNode : atomix3.metadataService().getMetadata().bootstrapNodes()) {
    Node node = atomix3.clusterService().getNode(availableNode.id());
    logger.info("node {} is in state {}.", node, node.getState());
}
```
```
18:09:51.565 [main] INFO  MDC[] io.carousel.it.Bootstrap - node StatefulNode{id=server3, type=DATA, endpoint=127.0.0.1:5003} is in state ACTIVE.
```

**Comment by johnou** [comment]
After checking the code I think this makes sense. node state is only tracked in StatefulNode which is what clusterService uses, while metadataService uses ReplicatedNode. If you want to check if a node is available via metadataService you should use `tombstone()`.

**Comment by johnou** [comment]
@pawel-kaminski-krk good to close?

**Comment by pawel-kaminski-krk** [comment]
well I dont understand what is the purpose of the api for metadata service. maybe remove it ... it is just confusing

**Comment by pawel-kaminski-krk** [comment]
close it

**Comment by johnou** [comment]
@kuujo wdyt?

**Comment by johnou** [comment]
@kuujo poke

**Comment by kuujo** [comment]
I think we can probably consolidate the `ClusterService` and `ClusterMetadataService` if we want.

Currently, the `ClusterMetadataService` manages the persistent configuration which defines the `DATA` nodes in the cluster. Data nodes must be explicitly added/removed since they’re used in the Raft protocol.

Conversely, the `ClusterService` does failure detection and allows stateless `CLIENT` nodes to join/leave the cluster just by disconnecting.

So `ClusterMetadataService` provides a managed `DATA` node configuration that doesn’t change unless explicitly, and `ClusterService` is the high level API that provides a dynamic configuration.

**Comment by kuujo** [comment]
Those seem like two different-enough responsibilities to me, but I don’t mind being overridden. Either way seems reasonable to me.

But this could just be an issue of lack of documentation as well.

**Comment by johnou** [comment]
@kuujo so we could just remove the getter metadataService() and consider ClusterMetadataService an internal service?

**Comment by pawel-kaminski-krk** [comment]
if something doesn't have to be public, make it private! I agree, in my opinion it just brings to much confusion.
