### ISSUE TITLE
question about raft

### ISSUE THREAD

**Issue by jacky1193610322** [atomix/atomix#402]
recently, I'm learning the raft, I find the copycat to help me learn, 
but there are some questions.
the event happens in the following.

the client sends the request to the leader.
the leader broadcast the proposal to all follower.
the leader commit when receiving the success of the majority of followers

1. the follower will respond the success=false or doesn't respond to the leader when an error happened in the middle of handling the proposal?

I mean each system call maybe fail. for example malloc or write. if the error happens, will the follower respond the failure or doesn't respond when an error happens in the middle of handling the proposal?
for example.
p_malloc = malloc(20);
if (p_malloc == NULL){
return error_code;
}
handle(propose);
(the code written in c, in java it's some exception)

malloc is just an example, I just want to describe an error happen in the middle of handling the proposal, the proposal doesn't handle successfully, Will the follower respond the false or doesn't respond to the leader?

2. what happened when the leader cannot get the response from the majority but the network is ok?

the raft says: the leader will commit when it receives success from the majority of nodes,
but if it doesn't exceed the quorum, for example, there are 5 nodes a,b,c,d,e.
a is the leader, it receives the client's request, then broadcast the propose to the followers, if c,d,e fail with full disk or something but the network is ok(I just want to say some error happen in the middle of handling the propose, for example, write disk return error), it will respond the failure to the leader or doesn't respond. in the end, the leader only receives a success from b, what should the leader respond the client?
a) the leader respond the client failure, but the b success, the raft doesn't support delete operation to delete the value in the b, if the leader down, and the follower b maybe become the leader which will commit the value later，and when the client read it, it has the value, but we just respond the client failure.
b) if the leader doesn't response the client，the client will timeout,
it's ok because timeout means success or failure, but I think it's not good.

**Comment by kuujo** [comment]
In the case of Atomix, when an error occurs during handling of an AppendEntries RPC (called AppendRequest) we return an error to the leader. It’s probably important here that the follower _not_ return false, because that indicates that the leader should decrease the follower’s nextIndex, causing the leader to retry with more entries from an earlier point in the log. The false response is supposed to indicate that the entries replicated by the leader to not align with the follower’s log, and nothing more. So an error response makes more sense to allow the leader to handle the failure without necessarily treating it as an inconsistent log.

If a change can’t be committed for any reason, in Atomix the leader ultimately rejects the client’s request. But part of the problem here is that a change may still have been appended to the leader’s log and thus may later be committed after rejecting the client’s request. That’s the reason we use sessions: clients assign a sequential ID to requests, and state machines ensure a given command is only applied once regardless of how many times it was written to the log and committed. In practice, if this type of scenario were to occur in Atomix, client’s would retry their commands until their session expired (due to not being able to commit keep-alives) and then disconnect until the servers’ exceptions were fixed.

But something else interesting to note here is that Atomix has a soft and hard limit on the amount of disk space that can be consumed before it will block all writes and compact logs. When the soft limit is reached, compaction is forced regardless of the load on the node, and when the hard limit is reached writes are blocked until logs are compacted and disk space is freed.

**Comment by jacky1193610322** [comment]
Thank you very much.

**Comment by johnou** [comment]
@jacky1193610322 please close the issue if you have no further questions.

**Comment by jacky1193610322** [comment]
sorry, I just see the mail, sorry.
