### ISSUE TITLE
Stale RaftClusterContext metastore configuration

### ISSUE THREAD

**Issue by johnou** [atomix/atomix#411]
When a node starts up nodes found in the metastore configuration are not validated which is a problem in the following scenario.

bootstrap nodes {node 1}
node 2 joins the cluster
node 1,2 are killed
node 1 will fail to start until node 2 comes back up.

**Comment by johnou** [comment]
@kuujo is a dynamic cluster of data nodes supported or only client nodes?

**Comment by kuujo** [comment]
We should double check this, but it sounds like expected behavior. Part of the configuration of data nodes is persistent because of the Raft partitions. Once a second node is added, all the Raft partitions should effectively be reconfigured to two nodes. If you kill either node, the configuration is still two nodes and so two nodes have to be available for nodes to complete startup. Conversely, if you remove one of the nodes then that should resize the partitions back down to one and allow a single node to be started.

**Comment by johnou** [comment]
@kuujo and resizing a partition is not yet supported correct?
