### ISSUE TITLE
empty documentation?

### ISSUE THREAD

**Issue by brunolellis** [atomix/atomix#575]
Hello,
I am trying to read Atomix's website documentation, but it is just empty. Are there any errors?

What happens:
![image](https://user-images.githubusercontent.com/491837/40579170-1e358584-60f8-11e8-8ae1-597d147be812.png)

Thanks!

**Comment by kuujo** [comment]
Please search issues before posting new issues (#569), and website issues belong in the website repository:
https://github.com/atomix/atomix.github.io

If documentation does not exist then that’s because it hasn’t been written. A couple suggestions:
• We could use help writing the documentation or
• Maybe it would be helpful to submit a PR to the website repo to mark those pages as in progress

In general, the most important documentation is being written first.

**Comment by kuujo** [comment]
BTW if you do need usage documentation then click through to the relevant sections and see if the documentation is there. Th I website is not entirely empty.

**Comment by brunolellis** [comment]
Sorry. I just found some old links (+2 years ago) on reddit pointing to the documentation section comparing Atomix to Hazelcast. So I thought it was a problem with the website.

**Comment by kuujo** [comment]
It’s not a problem. The website just clearly needs to be updated with at least some notice about the documentation, and all the Atomix repos need more clear and visible instructions on submitting issues to avoid duplicates and ensure they make it to the correct queue.
