### ISSUE TITLE
Notification support for DistributedQueue

### ISSUE THREAD

**Issue by madjam** [atomix/atomix#60]
Producer-Consumer is a common setting in which a queue is used. Currently `DistributedQueue`'s `poll` returns `null` if the queue is empty. This requires a consumer to `poll` the queue at regular intervals to see if there are items in the queue ready for processing. Needless to say this is inefficient. A better approach would be something akin to long polling. A consumer will register a listener to get notified when the items are added to an empty queue. On receiving this notification the consumer will `poll` to get items out of the queue.

**Comment by kuujo** [comment]
+1 totally. This should be easy.

**Comment by kuujo** [comment]
Here are some questions: would the intended behavior of this be to push queued items to the first available consumer, or to a specific consumer? How important it is that order be maintained in *processing* queued items? In other words, should item 1 be processed by consumer x before item 2 is processed by consumer y? That would slow down the application significantly. I suppose the naive implementation would be to just push items to the first available consumer and effectively ignore order. But that's maybe application specific and could be provided by a configuration (support for resource configurations needs to be added in another issue).

**Comment by madjam** [comment]
I was initially considering an approach where entries are always pulled and never pushed.
What gets pushed is a notification that is generated when items are added to an (previously) empty queue. An application on receiving this notification will will try to complete any active long poll requests by re-polling the queue. If the latest poll returned a `null` entry because some other application beat it to queue entry then this application will continue it its earlier state where it will re-poll on receiving the next notification.

The advantage I saw with this approach is that the consumer can operate at at its own speed with the queue serving as a buffer.

**Comment by kuujo** [comment]
Ahh I gotcha. That seems nice. There is definitely a lack of flow control in publishing events to clients, so OOM on the client is plausible if the server is pushing items to the client. Also, we (I) should keep in mind that there's a lot of overhead to sending events to clients, particularly if they're already stored in the state machine anyways. Publishing an event that gets queued on the client requires that a majority of servers hold the event in memory for fault tolerance until the client actually processes it. So that means each server is storing twice the necessary memory for a queue. Therefore, events should really not be used if they'll duplicate state machine state.

Just a notification to pull would be great.

**Comment by jhalterman** [comment]
I'm wondering if DistributedQueue (and DistributedTopic for that matter) will be used in place of a message broker for some use cases, as opposed to just being used as a data structure. As a message broker replacement, we should consider how client failures would be handled, where a client needs to be re-sent some messages. An AMQP-like approach would have the client ack messages else they be resent after some time period. A Kafka-like approach would allow a client to (re)-request any messages by index/range, which seems like more of a natural fit for the underlying log structure we're working with.

**Comment by kuujo** [comment]
Good point. If it's used for messaging or as a work queue then polling on clients could cause issues. Even if an event is sent to the client and the client requests and gets an item from the queue, that doesn't mean the client successfully processed it. It would be feasible to have a client essentially take out a lease on an item (or items) in the queue and ack those items on the next poll. In order to ensure concurrent consumers can progress we would lose total ordering, but as long as it's documented that's fine with me.

DistributedTopic doesn't have that issue since it publishes events through the session events system which is fault tolerant and handle acks itself. Also, DistributedTopic doesn't particularly guarantee that any consumer will see any message, only that all consumers will see all messages sent while their session was open *so long as they keep their session open*.

**Comment by madjam** [comment]
A work queue is the exactly use case I had in mind. In such a setting there are one or more producers feeding one or more consumers. Consumers are designed to be idempotent. A poll is effectively taking a lease and successfully processed items are removed from the queue by an explicit remove (that can be optionally piggy backed on a subsequent poll). If a consumer fails after taking a lease or fails to extend the lease (before it expires), all its in-flight items will be made available for another consumer to process. There are no strict ordering guarantees expected from the queue in this setting.

If strict ordering guarantees are required, we can constrain the number of consumers to one per queue. If the application semantics allows greater degree of parallelization is still possible to create multiple queues (partitions) with each being served by a separate consumer.

**Comment by kuujo** [comment]
Awesome that sounds good. Should be easy to implement.

**Comment by davidecaroselli** [comment]
Hi guys!

Any update on this issue? Is it implemented in the latest release?

**Comment by kuujo** [comment]
Instead of implementing this in `DistributedQueue`, this use case is now fulfilled by group messaging.

```java
DistributedGroup group = atomix.getGroup("message-group").join();
MessageProducer.Options options = new MessageProducer.Options()
  .withExecution(MessageProducer.Execution.SYNC)
  .withDelivery(MessageProducer.Delivery.RANDOM);
MessageProducer<String> producer = group.messaging().producer("foo");
producer.send("Hello world!").thenRun(() -> {
  // Message acked
});
```

```java
DistributedGroup group = atomix.getGroup("message-group").join();
LocalMember member = group.join().join();
MessageConsumer<String> consumer = member.messaging().consumer("foo");
consumer.onMessage(message -> {
  ...
  message.ack();
});
```

http://atomix.io/atomix/docs/groups/#broadcast-messaging
