### ISSUE TITLE
Seed Nodes/Gossip

### ISSUE THREAD

**Issue by hvandenb** [atomix/atomix#66]
Maybe there is already a way in Atomix to do this, but could we not use the Gossip protocol to discover other members? This way you only need to know one of two seed nodes and the others can be discovered. This is something similar that [Akka Cluster](http://doc.akka.io/docs/akka/snapshot/java/cluster-usage.html) does.

**Comment by kuujo** [comment]
Sorry, I had to wait to get enough time to answer this one.

So, this is a sort of a complex with respect to Raft. A typical Raft cluster only consists of 3 or 5 or 7 nodes, and the number of nodes is fixed most of the time. Similarly, the core of an Atomix cluster will typically be 3 or 5 nodes and that core cluster shouldn't change too frequently. The reason that membership changes are expensive is because the full commit log must be replicated to new servers, and because a majority of Raft nodes must effectively vote on all commits, adding too many core nodes to a cluster can slow it down.

Atomix solves this by providing both a stateful and stateless implementation of the Atomix interface. AtomixReplica is an Atomix node that stores state. AtomixClient is an Atomix node that doesn't. Replicas and clients both provide the exact same consistency guarantees, but clients can fail without impacting the cluster's quorum size. So, an Atomix cluster can have 3 or 5 replicas and the rest clients. In the case of clients, they *do* only need to know the Address of at least one available server at startup. A client will proxy a request through the first live server it can contact to register a session. Once a client's session is open, it will receive an updated list of all servers in the cluster. Thereafter, it will receive updates to cluster membership periodically with keep-alive responses.

But TBH I still don't think this is ideal for Atomix. I've always wanted to ease the limitations of Raft quorums to make the cluster more flexible. To that end, I'm finishing up a PR for Atomix this week that will allow Atomix stateful servers/replicas to scale much larger than 3/5/7 nodes and allow Raft nodes to be easily replaced when they die. This is essentially an extension of Copycat's Raft algorithm to make Atomix clusters more elastic. An Atomix cluster will be able to have any number of servers/replicas, and Atomix will promote certain nodes to participate in the Raft consensus algorithm according to the desired level of fault tolerance. Additionally, servers/replicas will behave like clients in that they'll be able to locate the rest of the cluster through a single live node. Ultimately, though, state changes will always go through the Raft cluster, and so Atomix will never be completely HA.

**Comment by jhalterman** [comment]
Adding to @kuujo's response - Copycat does use a gossip protocol for that exact purpose, among other things. I don't think it's specifically described as a gossip protocol in the docs (right now) though since that and some of the other intra-node gossip that takes place is actually just part of the Raft algorithm.

**Comment by madjam** [comment]
To add to good points already made:
- **Replicas** (nodes that maintain state) need to be aware of the cluster configuration in order to participate in the Raft protocol. Almost all activities (soliciting votes, replicating log entries) rely on the notion of a quorum (a cluster majority) and for that reason a replica node needs to be configured with the set of the members that are part of the cluster and this information cannot be discovered via gossip. Updates to the cluster configuration need to be managed via the Raft protocol to ensure we don't we don't end up with split brain scenario.
- **Clients** (nodes that are stateless) only need to be aware of at least one live replica for them to successfully submit updates and queries. In a deployment scenario this can be achieved by fronting the replicas with a proxy that will route new client registration requests to any one of the available replica nodes. After this initial interaction the client will learn about the full set of replica nodes that are part of the cluster and can directly contact a replica node depending on its chosen connection strategy.
