### ISSUE TITLE
The performance of this raft implementation.

### ISSUE THREAD

**Issue by nkorange** [atomix/atomix#944]
I don't see any wiki shows the benchmark test result of atomix. Is there any report recording how fast is this raft implementation?

**Comment by kuujo** [comment]
I haven’t done performance benchmarks on the Raft implementation alone in a very long time. We typically only run benchmarks on our entire system (ONOS) for each release. The last time I ran and recorded benchmarks for Atomix itself was after the Raft architecture change between 1.x and 2.x (which is the same Raft implementation as in 3.x). Those benchmarks are on a sharded system, though, which is what Atomix is, so they are not necessarily representative of the performance of the Raft implementation itself. I just made public some of the notes for those benchmarks [here](https://docs.google.com/spreadsheets/d/1bWWN_vvJ723yTRkPlMgOIJW6lUlzMzC0IGDc510CrdM/edit?usp=sharing).

Since we do have a benchmarking application that can be configured to use a single partition or multiple partitions, I think we can keep this open to ensure those benchmarks get run and recorded again since a lot has changed (including the messaging layer, the Raft log, etc) since they were last run. I can try to find some spare time to run them again soon.

**Comment by kuujo** [comment]
Long term, though, we need to add a reusable benchmarking application to this project. Maybe I can copy some of the code over from the ONOS benchmarking application to run them outside the Karaf container.

**Comment by kuujo** [comment]
Okay, I’m working on a benchmark for Atomix itself. The idea is that another node type can be deployed with `./bin/atomix-bench`. These nodes are special nodes designed to run benchmarks. Then the `atomix-bench` script can be used to `run` a benchmark on whatever number of `atomix-bench` have been deployed. When the benchmark is run, a REST API endpoint `POST /v1/bench` will be called with a configuration. That will create and return a test ID. The test configuration will be distributed to all the atomix-bench nodes via an `AtomicValue` primitive. The benchmark nodes will partition the operations and run them, then send statistics back to the node that started the benchmark. That node will aggregate and record the statistics in a `DistributedMap`. The `atomix-bench` script can fetch progress reports via `GET /v1/bench/1/progress` and the result via `/v1/bench/1/result`.

**Comment by nkorange** [comment]
@kuujo Great to see you are doing this, I'm looking forward to the outcome of your work. I'm going to download this project and test it myself too.

**Comment by natraj09** [comment]
@kuujo interested in the benchmark report as well .  I looked at the public excel sheet you had shared , the results look promising. Can you also share info (cores, memory) about  the specification of nodes used in the  test.

**Comment by johnou** [comment]
https://github.com/atomix/atomix-bench
