### ISSUE TITLE
how to listen the leader node change?

### ISSUE THREAD

**Issue by LQ-Gov** [atomix/atomix#945]
hello!
thank for you share the library,I have a question in used it,I want to listen the leader node change,What shall I do？i don't find it in your document website.

My atomix version is 3.0.8.

thanks.

**Comment by kuujo** [comment]
You had the right idea asking on chat, but we’ve moved to Slack. Nevertheless, here’s the response from Gitter:
https://atomix.io/docs/latest/user-manual/primitives/LeaderElection/ 

> There is a way to get Raft partition leaders, but those are just informative methods. The (strongly) recommended way to do any sort of leader election is using the leader election primitives which provide events, support for multiple leaders, support for leader transfer, prioritization, etc. Raft is not a good general leader election algorithm. The leader election primitives are.

**Comment by kuujo** [comment]
BTW the Raft leaders can be read by e.g.

```java
atomix.getPartitionService().getPartitionGroup(“raft”).getPartition(1).primary();
```

If we do need events for partition leader changes we can reopen this and they should be fairly simple to add to the `Partition` interface. One reason I could think of to do this is to help with co-locating processing with primaries to avoid a RTT.

**Comment by robvarga** [comment]
Hi Jordan,
one of the big things I would need in my project is exactly such events on the Partition to allow my processing to be robustly distributed in my cluster and just let Atomix manage the placement of my processing partitions. 
So it is a definite +1 vote from me. Would it be possible (without the expectation of any timeline) to just reopen this ticket so that I know where to look to see the status of this feature?
Thanks and best regards,
Robert

**Comment by kuujo** [comment]
Yes absolutely. We should add these. It should be a relatively straightforward change. Maybe I can take it on next week.
