### ISSUE TITLE
Missed events not receiving on recovery of node?

### ISSUE THREAD

**Issue by evrooije** [atomix/atomix#976]
I am playing around with Atomix Raft and events. I registered an event listener on a DistributedMap. I do a call to a websocket and add a value to the map in the websocket's frame handler. This correctly sends the event to all 3 nodes in my cluster.

I then stop node 3. Now I add a value again to the map after which node 1 and 2 correctly receive the notification. When I startup node 3 again, the event however does not fire/ is not "replayed".

I would expect that the replication log entries would be used to update the state of node 3 after recovery of the nodes, and that each log entry that was appended during the node's downtime would be replicated and then trigger any missed events in node 3. But seemingly the log is not used for the event notifications?

Is my assumption correct? Or maybe was this event notification system not meant for doing things like this (making this a feature request)? Many thanks in advance!

```java
DistributedMap<Object, Object> map = atomix.mapBuilder("test").build();
map.addListener(event -> {
	System.out.println("Event " + event.key() + " = " + event.newValue());
});

// snip to some Vertx3 websocket handler>

map.put(key, value);
```

Config (for member1, member2 and 3 have similar configs except for of course the IDs, ports and different data directories as this cluster runs on a single machine):
```
cluster {
  node {
    id: member1
    host: 127.0.0.1
    port: 11000
  }
  
  multicast.enabled: true

  discovery {
    type: multicast
    broadcastInterval: 1s
  }

  protocol {
    type: swim
    broadcastUpdates: true
    probeInterval: 1s
    failureTimeout: 5s
  }
}

managementGroup {
  type: raft
  partitions: 1
  members: [member1, member2, member3]
  storage {
    directory: "mgmt"
  }
}

partitionGroups.data {
  type: raft
  partitions: 3
  members: [member1, member2, member3]
  storage {
    directory: "pg"
  }
}
```

**Environment**

 - Atomix: 3.1.4
 - Atomix Vertx: 1.0.0-SNAPSHOT
 - OS: Windows 10 Enterprise
 - JVM 1.8.0

**Comment by kuujo** [comment]
This is a good and frequent question. What you describe is the intended behavior, and there are some design and technical reasons why that’s the case...

Raft does replay logs and thus one would think it should replay events to consumers as well. But primitives are in general a real-time abstraction based on replicated state machines. When you e.g. read a key in a distributed map, you get only the most recent value visible to the client, and the client generally doesn’t have access to the history of the primitive. Events are - in most cases - similarly real-time abstractions. When a key in a map is updated, an event is sent to all currently registered listeners. Listeners that are not registered at the time the event was generated will never see it.

There are technical reasons for these semantics of state machine based primitives because there are complications with replaying _events_ generated from Raft logs (and other protocols) to clients. One of the core components of the Raft algorithm is log compaction. As changes are written to the Raft log, the log consumes more and more disk space. Eventually Atomix takes snapshots of the primitive state machines and deletes logs from disk. But the problem is, you can’t both free up disk space with snapshots _and_ preserve the history of events. So you’re always going to end up with a partial history of events, and deleting events from an event history is not something Atomix should do quietly.

The original Raft implementation did have a way of preserving _relevant_ events. State machines marked changes that no longer contributed to their state, and the servers continuously removed unnecessary changes from disk. This type of algorithm could be used to produce only relevant events to clients, but we moved away from the algorithm since it makes state machines much more complicated.

There are also some technical details of the Raft implementation and primitive abstraction that would make replaying events rather inefficient. In the case of Raft, most primitive are partitioned among multiple Raft clusters, and each Raft cluster stores changes and manages state machines for many primitives. In order to replay all events to a listener, the events would have to be read and replayed when that listener is registered. And because the logs within each partition are mixes of operations for all primitive state machines, that would mean each partition would have to replay their entire log and filter mostly irrelevant operations to get the operations relevant to the state machine to which the listener was added.

Furthermore, primitive events are not themselves written to Raft logs. Rather, events are derived from the current state of the primitive. That means replaying events to a listener would require re-building a separate instance of the primitive’s state machine used only for generating events to the client. Depending on the number of listeners and the size of the data, this could be very costly. Perhaps a solution to this _could_ be to store a separate log of primitive events as they’re generated by the state machine, but that would have significant performance costs.

I should note also that the behavior of primitive events is similar to what we see in other similar systems like ZooKeeper watches.

Given all this, replaying the full history of primitive events to listeners would be inefficient and is inconsistent with the architecture of the primitive abstraction. The position of Atomix is just that replaying a full history of events is inconsistent with its primitive interfaces. Well, all but the DistributedLog primitive. This is exactly why a Kafka-esque distributed log protocol and primitive were introduced in Atomix 3.1. The distributed log protocol is architected similarly to the other leader-based protocols in Atomix, but the implementation is designed to allow efficient replay of entries to consumers from arbitrary points in the log. IMO this is the right way to go about solving the event history problem. The replicated state machines on which the primitive abstraction is built are not suitable for replayable event histories. For cases where users need a complete history of events, the right abstraction is a log optimized for the use case.

**Comment by evrooije** [comment]
Thanks for the detailed explanation Jordan! :-) Now that you mention it when I searched the issues I think I was see log compaction mentioned in issue #21 and wondered about the implications. I have an embedded external store optimized for XML documents that I sort of wanted to "Raftify".

Mmmmh ... I guess that I can use event notifications for consistency across stores while the cluster is working properly and in case of node failures or adding new nodes I will have to replicate the external store by (re)building it using the information of the other nodes or a file copy (although the latter might require shutting down the other nodes ...).

Or alternatively for rebuilding I could introduce a distributed sorted map/ set with custom database commands for store and index operations (transaction log) whilst keeping a copy in the XML database. When I start a node (recovery) I will compare the transaction log in Atomix with what is stored in the external XML store. Having to replay the entire transaction log is a pain for adding new nodes (and would also be when replaying events from a Raft log), so for that scenario I might need to have the new node request a "file copy" or P2P copy of some sort anyways or just have patience while the new node rebuilds it's database.

Food for thought but I'll figure something out eventually ;-) thanks again & cheers,
Emiel

**Comment by evrooije** [comment]
Just for anyone wondering about possible ways of doing this. For I created a sorted event map keyed on an atomic counter and two atomic counters to keep track of the global and the local per node indexes.

```java
private DistributedMap<String, String> map;
private SortedMap<Long, String> events;
private AtomicCounter eventIndex;
private AtomicCounter localEventIndex;
```

During initialization I set ```events``` and ```eventIndex``` to the global, "shared" between the nodes, map and index. The local event index is also an atomic counter on the cluster, but I uniquely identify it using the member ID of the local node. I could store it locally, e.g. in a file or the database, but who knows it might come in handy to have it available as a distributed value in the cluster and why not leverage the Atomix state persistence capabilities here to simplify things ;-)

```java
map = atomix.<String, String>mapBuilder("test").build();
events = atomix.<Long, String>sortedMapBuilder("events").build();
eventIndex = atomix.atomicCounterBuilder("event-index").build();

String memberId = atomix.getMembershipService().getLocalMember().id().id();
localEventIndex = atomix.atomicCounterBuilder(memberId + "event-index").build();
```

I also add a listener, where I increment the local index on receipt of the event. Code to store the data in my embedded XML database should go here. As all nodes receive the event (including the node that received the original request), all nodes will then perform the database operation and increase their respective counters (if the database operation was successful of course).

```java
map.addListener(event -> {
	System.out.println("Processing event " + event.key() + " = " + event.newValue());
	localEventIndex.incrementAndGet();
});
```

Somewhere in my verticle on receive of some put request, I put the "event" on the event map using the next available global event index as key, concatenating the key and value from the web socket request as value (just for testing ATM):

```java
map.put(key, value);
events.put(eventIndex.incrementAndGet(), key + " = " + value);
```

Every time something is put on the map, the event is triggered and the local event index is incremented (and the embedded database code to be called).

Before I start the verticle on the local node, I actually check if any events were missed by comparing the local index of the node that joined the cluster and catch up if need be. Database code to catch up the local embedded database should go here as well.

```java
while (localEventIndex.get() < eventIndex.get()) {
	String event = events.get(localEventIndex.incrementAndGet());
	System.out.println("Catching up, processing event " + event);
}
```

There is quite some added latency, but there is a lot of room for improvement as well. I.e. make the web socket request processing async or fully delegating it to the distributed map's event handler, tuning with a local cache, I should probably use ```lastKey``` on the events map instead of a global ```eventIndex```, etc., etc. But in any case, this seems to do the trick in a very rudimentary manner, and making use of all the facilities offered by Atomix :-)
